export const userTypes = {
    CREATE_USER: "CREATE_USER",
    TOGGLE_LOGIN: "TOGGLE_LOGIN",
    LOGIN_USER_EMAIL_AND_PASSWORD: "LOGIN_USER_EMAIL_AND_PASSWORD",
    LOGIN_GOOGLE: "LOGIN_GOOGLE",
    DO_LOGOUT: "DO_LOGOUT",
};

export const loadingTypes = {
    TOGGLE_LOADING: "TOGGLE_LOADING",
};
